# Tomcat
server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 8090

# mysql
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://rm-8vbn0547n953gld488o.mysql.zhangbei.rds.aliyuncs.com:3306/db_mes_develop?useUnicode=true&characterEncoding=UTF-8
        username: fanteren
        password: fanteren123A
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

